In [17]:
import pandas as pd
import numpy as np

In [18]:
adj_mat_data = pd.read_csv('JRPASS+.csv',header=0,index_col=0,nrows=17)
print(adj_mat_data)
print(adj_mat_data.shape)

             Sapporo  Shiretoko  Noboribetsu  Muroran  Otaru  Esashi  Furano  \
Sapporo          0.0        0.0          1.0      0.0    1.0     0.0     1.0   
Shiretoko        0.0        0.0          0.0      0.0    0.0     0.0     0.0   
Noboribetsu      1.0        0.0          0.0      1.0    1.0     0.0     1.0   
Muroran          0.0        0.0          1.0      0.0    1.0     0.0     0.0   
Otaru            1.0        0.0          1.0      1.0    0.0     0.0     0.0   
Esashi           0.0        0.0          0.0      0.0    0.0     0.0     0.0   
Furano           1.0        0.0          1.0      0.0    0.0     0.0     0.0   
Biei             0.0        0.0          0.0      0.0    0.0     0.0     1.0   
Asahikawa        1.0        0.0          1.0      0.0    0.0     0.0     0.0   
Kushiro          0.0        1.0          0.0      0.0    0.0     0.0     0.0   
Abashiri         0.0        1.0          0.0      0.0    0.0     0.0     0.0   
Monbetsu         0.0        0.0         

In [19]:
adj_mat = adj_mat_data.values
adj_mat[np.isnan(adj_mat)] = 0
adj_mat = adj_mat + adj_mat.T
adj_mat[adj_mat > 0] = 1
print(adj_mat)

[[ 0.  0.  1.  0.  1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  1.  1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  1.  0.  1.]
 [ 0.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  1.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. 

In [20]:
df = pd.DataFrame(adj_mat, index=city, columns=city)
print(df)
df.to_csv('JRPASS+.csv')

             Sapporo  Shiretoko  Noboribetsu  Muroran  Otaru  Esashi  Furano  \
Sapporo          0.0        0.0          1.0      0.0    1.0     0.0     1.0   
Shiretoko        0.0        0.0          0.0      0.0    0.0     0.0     0.0   
Noboribetsu      1.0        0.0          0.0      1.0    1.0     0.0     1.0   
Muroran          0.0        0.0          1.0      0.0    1.0     0.0     0.0   
Otaru            1.0        0.0          1.0      1.0    0.0     0.0     0.0   
Esashi           0.0        0.0          0.0      0.0    0.0     0.0     0.0   
Furano           1.0        0.0          1.0      0.0    0.0     0.0     0.0   
Biei             0.0        0.0          0.0      0.0    0.0     0.0     1.0   
Asahikawa        1.0        0.0          1.0      0.0    0.0     0.0     0.0   
Kushiro          0.0        1.0          0.0      0.0    0.0     0.0     0.0   
Abashiri         0.0        1.0          0.0      0.0    0.0     0.0     0.0   
Monbetsu         0.0        0.0         

In [10]:
score_mat = pd.read_csv('Score.csv',header=0,index_col=0)
print(score_mat)

             Sapporo  Shiretoko  Noboribetsu     Muroran        Otaru  \
City                                                                    
View_1    695.000000      692.0       1034.0  202.000000  2199.000000   
Grade_1     4.500000        4.5          4.0    4.000000     4.000000   
View_2   1112.000000      486.0        265.0  114.000000   286.000000   
Grade_2     4.500000        4.0          4.5    4.000000     4.000000   
View_3   1394.000000      210.0        274.0   36.000000   291.000000   
Grade_3     4.000000        4.0          4.0    4.500000     4.000000   
Score    4569.166667     1966.0       2141.5  475.333333  3701.333333   

             Esashi       Furano    Biei  Asahikawa      Kushiro     Abashiri  \
City                                                                            
View_1    54.000000   524.000000   673.0     2179.0   507.000000   551.000000   
Grade_1    4.000000     4.000000     4.5        4.5     4.000000     4.500000   
View_2    30.00000

In [21]:
people = np.max(score_mat.values[[0,2,4]],axis=0)
energy = -np.log(people)
print(energy)
print(list(np.argsort(energy)))

[-7.23993259 -6.53958596 -6.94119006 -5.3082677  -7.69575799 -3.98898405
 -6.26149168 -7.16703788 -7.68662133 -6.228511   -6.31173481 -4.4543473
 -4.91998093 -6.21060008 -5.90263333 -3.61091791 -7.95366978]
[16, 4, 8, 0, 7, 2, 1, 10, 6, 9, 13, 14, 3, 12, 11, 5, 15]


In [22]:
city = adj_mat_data.columns
print(city)

Index(['Sapporo', 'Shiretoko', 'Noboribetsu', 'Muroran', 'Otaru', 'Esashi',
       'Furano', 'Biei', 'Asahikawa', 'Kushiro', 'Abashiri', 'Monbetsu',
       'Numuro', 'Wakkanai', 'Obihiro', 'Rumoi', 'Hakodate'],
      dtype='object')


In [23]:
nodes = [{'id':a} for a in city]
print(nodes)
#nodes

[{'id': 'Sapporo'}, {'id': 'Shiretoko'}, {'id': 'Noboribetsu'}, {'id': 'Muroran'}, {'id': 'Otaru'}, {'id': 'Esashi'}, {'id': 'Furano'}, {'id': 'Biei'}, {'id': 'Asahikawa'}, {'id': 'Kushiro'}, {'id': 'Abashiri'}, {'id': 'Monbetsu'}, {'id': 'Numuro'}, {'id': 'Wakkanai'}, {'id': 'Obihiro'}, {'id': 'Rumoi'}, {'id': 'Hakodate'}]


In [25]:
links = []
for index1, a in enumerate(adj_mat):
    for index2, b in enumerate(a):
        if b and index1>index2:
            if energy[index1]> energy[index2]:
                links.append({
                    'source':city[index1],
                    'target':city[index2],
                    'value':1
                })
            else:
                links.append({
                    'source':city[index2],
                    'target':city[index1],
                    'value':1
                })
links

[{'source': 'Noboribetsu', 'target': 'Sapporo', 'value': 1},
 {'source': 'Muroran', 'target': 'Noboribetsu', 'value': 1},
 {'source': 'Sapporo', 'target': 'Otaru', 'value': 1},
 {'source': 'Noboribetsu', 'target': 'Otaru', 'value': 1},
 {'source': 'Muroran', 'target': 'Otaru', 'value': 1},
 {'source': 'Furano', 'target': 'Sapporo', 'value': 1},
 {'source': 'Furano', 'target': 'Noboribetsu', 'value': 1},
 {'source': 'Furano', 'target': 'Biei', 'value': 1},
 {'source': 'Sapporo', 'target': 'Asahikawa', 'value': 1},
 {'source': 'Noboribetsu', 'target': 'Asahikawa', 'value': 1},
 {'source': 'Biei', 'target': 'Asahikawa', 'value': 1},
 {'source': 'Kushiro', 'target': 'Shiretoko', 'value': 1},
 {'source': 'Abashiri', 'target': 'Shiretoko', 'value': 1},
 {'source': 'Abashiri', 'target': 'Asahikawa', 'value': 1},
 {'source': 'Monbetsu', 'target': 'Asahikawa', 'value': 1},
 {'source': 'Numuro', 'target': 'Kushiro', 'value': 1},
 {'source': 'Wakkanai', 'target': 'Asahikawa', 'value': 1},
 {'sour

In [26]:
graph['nodes']

[{'id': 'Sapporo'},
 {'id': 'Shiretoko'},
 {'id': 'Noboribetsu'},
 {'id': 'Muroran'},
 {'id': 'Otaru'},
 {'id': 'Esashi'},
 {'id': 'Furano'},
 {'id': 'Biei'},
 {'id': 'Asahikawa'},
 {'id': 'Kushiro'},
 {'id': 'Abashiri'},
 {'id': 'Monbetsu'},
 {'id': 'Numuro'},
 {'id': 'Wakkanai'},
 {'id': 'Obihiro'},
 {'id': 'Rumoi'},
 {'id': 'Hakodate'}]

In [27]:
graph = {
    'nodes':nodes,
    'links':links
}

In [28]:
import json
with open('HakkaidoMap.json','w') as outfile:
    json.dump(graph, outfile)

In [29]:
all_data = {
    'graph':graph,
    'adj_mat':adj_mat,
    'energy':energy,
    'city':city,
    'people':people
}

In [31]:
import pickle
pickle.dump(all_data, open('Hakkaido_cleaned.p','wb'))